version: '2'
services:
  sidecar-restore-volumes:
      image: nutellinoit/sidecar-restore-volumes:latest
      restart: "no"
      environment:
        # - TAR_TO_RESTORE=${TAR_TO_RESTORE}
        - TAR_PATH=${TAR_PATH}
        - S3_BUCKET=${S3_BUCKET}
        - S3_KEY=${S3_KEY}
        - S3_SECRET=${S3_SECRET}
        - S3_HOST=${S3_HOST}
        - S3_PROTOCOL=${S3_PROTOCOL}
        - TRANSFORM_FROM=${TRANSFORM_FROM} # optional, moving files post extraction
        - TRANSFORM_TO=${TRANSFORM_TO} # optional, moving files post extraction
      volumes_from:
        - wordpress:rw  # example mounted volumes for backups
###################
##### example wordpress install
  wordpress:
      image: wordpress
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./wp-app:/var/www/html